my_frame/main/routes.py
from flask import Blueprint, render_template
from my_frame.main.utils import first_three_images_in_db
from my_frame.main.forms import NewsletterSignup
from flask import flash, request

main = Blueprint('main', __name__)

@main.route("/", methods=['GET', 'POST'])
@main.route("/home", methods=['GET','POST'])
def home():
    images = first_three_images_in_db()
    form = NewsletterSignup()
    if request.method == "POST":
        if form.validate_on_submit():
            flash(f'Thank you for your interest, we will be adding a newsletter soon!', 'success')
        else:
            flash(f'Please enter a valid email address.', 'danger')
    return render_template('home.html', title='MyFrame', image=images, form=form)

@main.route("/setup")
def setup():
    return render_template('setup_guide.html', title='MyFrame - Setup')

my_frame/posts/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, abort
from flask_login import current_user, login_required
from my_frame import db
from my_frame.models import Image_Post
from my_frame.posts.forms import PostForm, SetActiveForm
from my_frame.posts.utils import fn_to_uuid, upload_file_to_s3, del_file_from_s3, s3bucket_getfile
from my_frame.config import Config

posts = Blueprint('posts', __name__)


@posts.route("/image/new", methods=["GET","POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_uuid = fn_to_uuid(form.picture.data)
            upload_file_to_s3(picture_uuid, bucket_name=Config.S3_BUCKET)
            uuid_filename = picture_uuid.filename
            post = Image_Post(image_uuid=uuid_filename, title=form.title.data, author=current_user)
            db.session.add(post)
            db.session.commit()
            flash('Your image has been uploaded!', 'success')
            return redirect(url_for('users.account'))
        else:
            flash('Please select an image!', 'danger')
    return render_template('create.html', title='MyFrame - New Image', form=form, legend='Image Title')

@posts.route("/edit/<int:id>", methods=["GET","POST"])
@login_required
def edit(id):
    image = Image_Post.query.get_or_404(id)
    if current_user.id != image.user_id:
        abort(403)
    form = PostForm()
    form2 = SetActiveForm()
    image = Image_Post.query.get_or_404(id)
    single_image = image
    if form2.validate_on_submit() and "set_active" in request.form:
        current_user.active_image = single_image.image_uuid
        db.session.commit()
        flash(f'Your active image has been changed to {single_image.title}', 'success')
    if form.validate_on_submit():
        image.title = form.title.data
        db.session.commit()
        flash("Your image has been updated!", 'success')
        return redirect(url_for('posts.edit', id=image.id))
    elif request == "GET":
        form.title.data = image.title
        form.picture.data = image.image_uuid
    return render_template('edit.html', title='MyFrame - Update Image', image=image,
                           form=form, form2=form2, legend='Update Post')

@posts.route("/edit/<int:id>/delete", methods=["POST"])
@login_required
def delete(id):
    image = Image_Post.query.get_or_404(id)
    image_uuid = image.image_uuid
    if current_user.id != image.user_id:
        abort(403)
    db.session.delete(image)
    db.session.commit()
    del_file_from_s3(image_uuid)
    flash('Your post has been deleted!','success')
    return redirect(url_for('users.account'))

@posts.route("/browse", methods=["GET","POST"])
#@login_required
def browse():
    page = request.args.get('page', 1, type=int)
    images = Image_Post.query.order_by(Image_Post.date_posted.desc()).paginate(page=page, per_page=12)
    return render_template('browse.html', title='MyFrame - Browse Images', image=images)

@posts.route("/posts/<int:id>", methods=["GET","POST"])
@login_required
def view_single_image(id):
    image = Image_Post.query.get_or_404(id)
    image_uuid = image.image_uuid
    form = SetActiveForm()
    if form.validate_on_submit():
        current_user.active_image = image_uuid
        db.session.commit()
        flash(f'Your active image has been changed to {image.title}', 'success')

    return render_template('view_single_image.html', form=form, title='MyFrame - Browse Images', fn=image_uuid, image=image)

my_frame/users/routes.py
from flask import Blueprint
from my_frame.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm
from flask import render_template, url_for, flash, redirect, request
from my_frame.models import User, Image_Post
from my_frame import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from my_frame.users.utils import user_images_group, send_reset_email
from my_frame.posts.utils import upload_file_to_s3, fn_to_uuid, del_file_from_s3
from my_frame.config import Config


users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data.lower(), email=form.email.data.lower(), password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='MyFrame - Register', form=form, legend='New Post')

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check your email and password and try again!', 'danger')
    return render_template('login.html', title='MyFrame - Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=["GET","POST"])
@login_required
def account():
    form = UpdateAccountForm()
    user_images = user_images_group()
    if form.validate_on_submit():
        if form.picture.data:
            del_file_from_s3(current_user.profile_picture)
            picture_uuid = fn_to_uuid(form.picture.data)
            upload_file_to_s3(picture_uuid, bucket_name=Config.S3_BUCKET)
            current_user.profile_picture = picture_uuid.filename
        current_user.username = form.username.data.lower()
        current_user.email = form.email.data
        db.session.commit()
        flash(f'Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_picture = current_user.profile_picture
    return render_template('account.html', title='MyFrame - Account',fn=profile_picture, form=form, images=user_images)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    images = Image_Post.query.filter_by(author=user).order_by(Image_Post.date_posted.desc()).paginate(page=page, per_page=15)
    return render_template('browse_user.html', image=images, user=user)

@users.route("/reset_password", methods=["GET","POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instruction to reset your password','info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='MyFrame - Reset Password', form=form)

@users.route("/reset_password/<token>", methods=["GET","POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token,', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been changed. You may now login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='MyFrame - Reset Password', form=form)

my_frame/templates/browse.html
{% extends 'layout.html' %}

{% block content %}
<section class="p-5">
    <div class="container">
        <div class=''>
            <div class="text-center">
                <h2>All Images</h2>
            </div>
                {% for image in image.items %}
                {% if loop.index0 % 3 == 0 %}
            <div class="row text-center mt-3">
                {% endif %}
                <div class="col">
                    <div class="card border-1">
                        <a href="{{ url_for('posts.view_single_image', id=image.id)}}"><img class="card-img sized-256" src="https://piframebucket.s3.us-west-1.amazonaws.com/{{image.image_uuid}}"></a>
                        <div class="card-body d-none d-md-block">
                            <p class="mb-0 mt-0">{{ image.title }}</p>
                            <p class="mt-0">{{ image.date_posted.strftime('%m-%d-%Y') }}</p>
                        </div>
                    </div>
                </div>
                {% if loop.last and loop.index0 % 3 == 1 %}
                <div class="col">
                    <div class="card border-0">
                        <div class="card-body">
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if loop.last and loop.index0 % 3 == 0 %}
                <div class="col">
                    <div class="card border-0">
                        <div class="card-body">
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card border-0">
                        <div class="card-body">
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if loop.index0 % 3 == 2 or loop.last %}
            </div>
            {% endif %}
            {% endfor %}

<!-- Loop through the number of pages to display a link for each-->
    {% for page_num in image.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
<!-- Check for the active page and set the link to "Active"-->
            {% if image.page == page_num %}
            <a href="{{ url_for('posts.browse', page=page_num)}}"
               class="btn btn-dark">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('posts.browse', page=page_num)}}"
               class="btn btn-outline-dark">
                {{ page_num }}
            </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

my_frame/templates/browse_user.html
{% extends 'layout.html' %}

{% block content %}
<section class="p-5">
    <div class="container">
        <div class=''>
            <div class="text-center">
                <h1>Posts by {{ user.username }} ({{ image.total }})</h1>
            </div>
                {% for image in image.items %}
                {% if loop.index0 % 3 == 0 %}
            <div class="row text-center mt-3">
                {% endif %}
                <div class="col">
                    <div class="card border-1">
                        <img class="card-img" src="{{ url_for('static', filename='images/user_uploads_sized/' + image.image) }}">
                        <div class="card-body d-none d-md-block">
                            <p class="mb-0 mt-0">{{ image.title }}</p>
                            <p class="mt-0">{{ image.date_posted.strftime('%m-%d-%Y') }}</p>
                        </div>
                    </div>
                </div>
                {% if loop.last and loop.index0 % 3 == 1 %}
                <div class="col">
                    <div class="card border-0">
                        <div class="card-body">
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if loop.last and loop.index0 % 3 == 0 %}
                <div class="col">
                    <div class="card border-0">
                        <div class="card-body">
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card border-0">
                        <div class="card-body">
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if loop.index0 % 3 == 2 or loop.last %}
            </div>
            {% endif %}
            {% endfor %}

<!-- Loop through the number of pages to display a link for each-->
    {% for page_num in image.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
<!-- Check for the active page and set the link to "Active"-->
            {% if image.page == page_num %}
            <a href="{{ url_for('posts.browse', page=page_num)}}"
               class="btn btn-dark">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('posts.browse', page=page_num)}}"
               class="btn btn-outline-dark">
                {{ page_num }}
            </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

my_frame/templates/edit.html
{% extends 'layout.html' %}
{% block content %}
<section class="p-5">
    <div class="container">
        <div class="text-center">
            <img class="card-img sized-256" src="https://piframebucket.s3.us-west-1.amazonaws.com/{{image.image_uuid}}">
            <h2 class="mb-3 mt-3">{{ image.title }}</h2>
            <p class="">Date Posted: {{ image.date_posted.strftime('%m-%d-%Y') }}</p>
        </div>
        <form method="POST" action="">
            {{ form2.hidden_tag() }}
            <div class="form-group mb-3 d-flex flex-column align-items-center">
                {{ form2.set_active(class="btn cstm-btn-red fw-bold white font-roboto mt-3 mb-2 btn-sm") }}
            </div>
        </form>

        <div class="mt-5 text-center">
            <form method="POST" action="">
            {{ form.hidden_tag() }}
                <div class="form-group mb-3 d-flex flex-column align-items-center">
                    <label class="form-label">Update Title</label>
                    <div>
                        {{form.title(class="form-control mb-1", placeholder='Enter New Title')}}
                    </div>
                    {{ form.submit(class="btn cstm-btn-red fw-bold white font-roboto mt-3 mb-2 btn-sm") }}
                </div>
            </form>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger mt-5" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete Image</button>
        </div>
    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Image?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete', id=image.id)}}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

my_frame/templates/home.html
{% extends 'layout.html' %}
{% block content %}

<!-- Hero -->
    <section class="bg-image text-light p-5 text-center">
        <div class="container">
            <div class="d-sm-flex justify-content-around align-items-center">
                <div>
                    <h1 class="font-roboto letter-spacing-wide header-shadow">MyFrame</h1>
                    <img class="img-fluid w-50 d-md-none" src="{{url_for('static', filename='images/miscellanious/my_frame.gif')}}" alt="My Frame Hero Banner">
                    <p class="lead font-roboto mt-3">The open source digital art frame.</p>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('main.setup') }}" class="mt-3 btn cstm-btn-red fw-bold white font-roboto">Setup Guide</a>
                    {% else %}
                        <a href="{{ url_for('users.register') }}" class="mt-3 btn cstm-btn-red fw-bold white font-roboto">Get Started</a>
                    {% endif %}
                </div>
                <img class="img-fluid w-50 d-none d-md-block" src="{{url_for('static', filename='images/miscellanious/my_frame.gif')}}" alt="My Frame Hero Banner">
            </div>
        </div>
    </section>

    <!-- Cards -->
    <section class="p-5">
        <div class="container">
            <div class="row text-center g-4">
                <div class="col-md d-flex">
                   <div class="card border-0">
                       <div class="card-body text-center">
                            <img src="{{url_for('static', filename='/images/miscellanious/github.png')}}" alt="" class="img-fluid mb-2">
                            <h3 class="card-title mb-3">Open Source</h3>
                            <p class="card-text">MyFrame is Open Source and we're always looking for new contributors!</p>
                        </div>
                        <div>
                            <a href="https://github.com/TroyLouis/MyFrame" class="mt-3 btn cstm-btn-red fw-bold white font-roboto">Github</a>
                        </div>
                   </div>
                </div>
                <hr class="d-block d-md-none">
                <div class="col-md d-flex">
                    <div class="card border-0">
                        <div class="card-body text-center">
                            <img src="{{url_for('static', filename='/images/miscellanious/check.png')}}" alt="" class="img-fluid mb-2">
                            <h3 class="card-title mb-3">Easy Setup</h3>
                            <p class="card-text">MyFrame is easy to setup and install. Grab your Rasberry Pi and start today! </p>
                        </div>
                        <div>
                            <a href="{{url_for('main.setup')}}" class="mt-3 btn cstm-btn-red fw-bold white font-roboto">Setup Guide</a>
                        </div>
                    </div>
                </div>
                <hr class="d-block d-md-none">
                <div class="col-md d-flex">
                    <div class="card border-0">
                        <div class="card-body text-center ">
                            <img src="{{url_for('static', filename='/images/miscellanious/community.png')}}" alt="" class="img-fluid mb-2">
                            <h3 class="card-title mb-3">Community</h3>
                            <p class="card-text">In the feed you will find eclectic images from our community members.</p>
                        </div>
                        <div>
                            <a href="{{ url_for('posts.browse') }}" class="mt-3 btn cstm-btn-red fw-bold white font-roboto">View Feed</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Recent User Uploads-->

    <section class="p-5 cstm-dark-bg">
        <div class="container">
            <h2 class="text-center mb-4 font-roboto white header-shadow">
                Recent Uploads From Our Community
            </h2>
            <div class="row">
                {% for image in image %}
                <div class="col-md d-flex justify-content-center align-self-center">
                    <div class="card-body text-center">
                        <a href="{{ url_for('posts.view_single_image', id=image.id)}}"><img class='sized-256' src="https://piframebucket.s3.us-west-1.amazonaws.com/{{image.image_uuid}}"></a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <!-- Accordion -->
    <section id="questions" class="p-5">
        <div class="container">
            <h2 class="text-center mb-4">
                FAQ
            </h2>
            <div class="accordion" id="accordionPanelsStayOpenExample">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                    <button class="accordion-button " type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                        What do I need to build a MyFrame digital art frame?
                    </button>
                  </h2>
                  <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                    <div class="accordion-body">
                        <p>To build a MyFrame digital art frame you will need the following:</p>
                        <ul>
                            <li>
                                Internet connection
                            </li>
                            <li>
                                A <a href="https://www.raspberrypi.com/">Raspberry Pi</a>
                            </li>
                            <li>
                                A mouse and keyboard to connect to your Pi
                            </li>
                            <li>
                                Computer monitor or LED screen with USB ports.
                            </li>
                        </ul>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                        How much does it cost to build a MyFrame digital art frame?
                    </button>
                  </h2>
                  <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                    <div class="accordion-body">
                        This project is completely free besides the hardware. The cost of hardware can vary greatly, especially if you purchase new. We were able to put one together for under $150!
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                        Do I need to know how to code to build a MyFrame digital art frame?
                    </button>
                  </h2>
                  <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
                    <div class="accordion-body">
                        No! Setup is easy and you don't need any programming experience. Check out the <a href="{{url_for('main.setup')}}">setup guide</a> for more information!
                    </div>
                  </div>
                </div>
              </div>
        </div>
    </section>

<!-- Email signup -->

    <section class="p-5 cstm-dark-bg">
        <div class="container">
            <h2 class="white font-roboto text-center header-shadow">Sign Up For Our Newsletter</h2>
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="d-flex justify-content-center mt-3">
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid", placeholder="Email Address") }}
                    {% else %}
                        {{ form.email(class="form-control mb-1", placeholder="Enter email") }}
                    {% endif %}
                </div>
                <div class="text-center mt-3">
                    {{ form.submit(class="btn cstm-btn-red fw-bold white font-roboto") }}
                </div>
            </form>
        </div>
    </section>

<!--Donation -->
    <section class="p-5">
        <div class="container text-center">
            <h2>Enjoying MyFrame? Consider a donation!</h2>
            <div class="d-none d-sm-block">
                <h5 class="text-muted mt-2">MyFrame is opensource and free. That doesn't mean we don't need money for servers and storage!</h5>
                <!--
                <p class="small mt-3 mb-0 ">Please consider a donation to help us cover the ongoing costs of hosting and storing data.</p>
                <p class="small mt-0">With enough donations, we will be able to spend more time on this project!</p>
                -->
            </div>
            <div class="row">
                <div class="col text-end">
                    <img class='img-fluid text-center' src="{{ url_for('static', filename='images/miscellanious/btc.png') }}">
                </div>
                <div class="col text-start">
                    <img src="{{ url_for('static', filename='images/miscellanious/eth.png') }}">
                </div>
            </div>
        </div>
        <div class="mt-2">
            <p class="text-center small-btc-address d-block d-sm-block d-md-none">0x42dd885f27b8258e904A593C73b32493EcE38781</p>
            <p class="text-center d-none d-md-block">0x42dd885f27b8258e904A593C73b32493EcE38781</p>

        </div>
    </section>

{% endblock %}

my_frame/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=  , initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/styles/main.css">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/miscellanious/Favicon_new.png')}}">
    <title>{{ title }}</title>
</head>
<body class="d-flex flex-column min-vh-100">
<!-- Navbar -->
    <nav class="navbar navbar-expand-lg cstm-dark-bg">
        <div class="container">
            <a href="{{ url_for('main.home') }}" class="navbar-brand fw-bold white">MyFrame</a>

            <button class="navbar-toggler navbar-dark"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navmenu"
            >
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navmenu">

                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="https://github.com/TroyLouis/MyFrame" class="nav-link white">Github</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('main.setup') }}" class="nav-link white">Setup Guide</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('posts.browse') }}" class="nav-link white">Browse Images</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('posts.new_post') }}" class="nav-link white">Upload Image</a>
                    </li>
                    <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{{ url_for('users.account') }}">My Profile</a>
                            <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
                        </div>
                    </div>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('users.login') }}" class="nav-link white">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} mb-0">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock%}


<footer class=" mt-auto cstm-dark-bg text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3 white">
    © 2022 | Troy Arnold
  </div>

</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>